def get_profile_details_event_list():
    return [{'value': 'active_suspend_reason', 'text': 'Active/Suspend Reason'},
            {'value': 'acquiring_sales_executive_id', 'text': 'Agent - Acquiring Sales Executive'},
            {'value': 'bank_branch_area', 'text': 'Agent - Bank Branch Area'},
            {'value': 'bank_branch_city', 'text': 'Agent - Bank Branch City'},
            {'value': 'bank_name', 'text': 'Agent - Bank Name'},
            {'value': 'contract_day_of_period_reconciliation', 'text': 'Agent - Contract Day/ Period of Reconciliation'},
            {'value': 'contract_expired_date', 'text': 'Agent - Contract Expiry Date'},
            {'value': 'contract_issue_date', 'text': 'Agent - Contract Issue Date'},
            {'value': 'contract_number', 'text': 'Agent - Contract Number'},
            {'value': 'contract_sign_date', 'text': 'Agent - Contract Sign Date'},
            {'value': 'contract_type', 'text': 'Agent - Contract Type'},
            {'value': 'contract_extended_type', 'text': 'Agent - Extended Type'},
            {'value': 'grand_parent_id', 'text': 'Agent - Grand Parent ID'},
            {'value': 'kyc_level', 'text': 'Agent - KYC Level'},
            {'value': 'national', 'text': 'Agent - National'},
            {'value': 'parent_id', 'text': 'Agent - Parent ID'},
            {'value': 'primary_expire_date', 'text': 'Agent - Primary Expire Date'},
            {'value': 'primary_identify_id', 'text': 'Agent - Primary Identity ID'},
            {'value': 'primary_identify_type', 'text': 'Agent - Primary Identity Type'},
            {'value': 'primary_issue_date', 'text': 'Agent - Primary Issue Date'},
            {'value': 'primary_place_of_issue', 'text': 'Agent - Primary Place of Issue'},
            {'value': 'secondary_expire_date', 'text': 'Agent - Secondary Expire Date'},
            {'value': 'secondary_identify_id', 'text': 'Agent - Secondary Identity ID'},
            {'value': 'secondary_identify_type', 'text': 'Agent - Secondary Identity Type'},
            {'value': 'secondary_issue_date', 'text': 'Agent - Secondary Issue Date'},
            {'value': 'secondary_mobile_number', 'text': 'Agent - Secondary Mobile Number'},
            {'value': 'secondary_place_of_issue', 'text': 'Agent - Secondary Place of Issue'},
            {'value': 'tertiary_mobile_number', 'text': 'Agent - Tertiary Mobile Number'},
            {'value': 'agent_type_id', 'text': 'Agent Type ID'},
            {'value': 'current_address', 'text': 'Current Address'},
            {'value': 'current_city', 'text': 'Current City'},
            {'value': 'current_commune', 'text': 'Current Commune'},
            {'value': 'current_country', 'text': 'Current Country'},
            {'value': 'current_district', 'text': 'Current District'},
            {'value': 'current_landmark', 'text': 'Current Landmark'},
            {'value': 'current_latitude', 'text': 'Current Latitude'},
            {'value': 'current_longitude', 'text': 'Current Longitude'},
            {'value': 'current_province', 'text': 'Current Province'},
            {'value': 'beneficiary', 'text': 'Customer - Benificiary'},
            {'value': 'citizen_card_date_of_issue', 'text': 'Customer - Citizen Card Date of Issue'},
            {'value': 'citizen_card_id', 'text': 'Customer - Citizen Card ID'},
            {'value': 'citizen_card_place_of_issue', 'text': 'Customer - Citizen Card Place of Issue'},
            {'value': 'device_description', 'text': 'Customer - Device Description'},
            {'value': 'device_id', 'text': 'Customer - Device ID'},
            {'value': 'middle_name', 'text': 'Customer - Middle Name'},
            {'value': 'occupations', 'text': 'Customer - Occupations'},
            {'value': 'passport_date_of_issue', 'text': 'Customer - Passport Date of Issue'},
            {'value': 'passport_id', 'text': 'Customer - Passport ID'},
            {'value': 'passport_place_of_issue', 'text': 'Customer - Passport Place of Issue'},
            {'value': 'place_of_birth', 'text': 'Customer - Place of Birth'},
            {'value': 'profile_picture_url', 'text': 'Customer - Profile Picture URL'},
            {'value': 'social_security_id', 'text': 'Customer - Social Security ID'},
            {'value': 'tax_id', 'text': 'Customer - Tax ID'},
            {'value': 'date_of_birth', 'text': 'Date of Birth'},
            {'value': 'email', 'text': 'Email'},
            {'value': 'first_name', 'text': 'First Name'},
            {'value': 'gender', 'text': 'Gender'},
            {'value': 'kyc_remark', 'text': 'KYC Remark'},
            {'value': 'kyc_status', 'text': 'KYC Status'},
            {'value': 'kyc_updated_timestamp', 'text': 'KYC Last Updated Timestamp'},
            {'value': 'last_name', 'text': 'Last Name'},
            {'value': 'nationality', 'text': 'Nationality'},
            {'value': 'permanent_address', 'text': 'Permanent Address'},
            {'value': 'permanent_city', 'text': 'Permanent City'},
            {'value': 'permanent_commune', 'text': 'Permanent Commune'},
            {'value': 'permanent_country', 'text': 'Permanent Country'},
            {'value': 'permanent_district', 'text': 'Permanent District'},
            {'value': 'permanent_landmark', 'text': 'Permanent Landmark'},
            {'value': 'permanent_latitude', 'text': 'Permanent Latitude'},
            {'value': 'permanent_longitude', 'text': 'Permanent Longitude'},
            {'value': 'permanent_province', 'text': 'Permanent Province'},
            {'value': 'primary_mobile_number', 'text': 'Primary Mobile Number'},
            {'value': 'profile_created_timestamp', 'text': 'Profile Created Timestamp'},
            {'value': 'profile_is_deleted', 'text': 'Profile Is Deleted'},
            {'value': 'profile_last_updated_timestamp', 'text': 'Profile Last Updated Timestamp'},
            {'value': 'unique_reference', 'text': 'Unique Reference'},
            {'value': 'user_id', 'text': 'User ID'},
            {'value': 'user_is_suspend', 'text': 'User Is suspended'},
            {'value': 'with_linked_bank_sof', 'text': 'With Linked Bank SOF'},
            {'value': 'with_linked_card_sof', 'text': 'With Linked Card SOF'}]