# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 08:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_auto_20170228_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentications',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
