# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0003_auto_20170301_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentications',
            name='correlation_id',
            field=models.CharField(default='', max_length=128),
        ),
    ]
